function stateNew=rk4(state,omega,par,dt)
k1=stateDerivative(state,par,omega);
tempState = stateAdd(state, k1, dt/2);

k2 = stateDerivative(tempState, par, omega);
tempState = stateAdd(state, k2, dt/2);

k3 = stateDerivative(tempState, par, omega);
tempState = stateAdd(state, k3, dt);

k4 = stateDerivative(tempState, par, omega);

stateNew.eta = state.eta + ...
    dt/6 * ( ...
    k1.eta + ...
    2*k2.eta + ...
    2*k3.eta + ...
    k4.eta );

stateNew.nu = state.nu + ...
    dt/6 * ( ...
    k1.nu + ...
    2*k2.nu + ...
    2*k3.nu + ...
    k4.nu );
end